# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bs?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: lihongfei
    # url
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:E://images

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    port: 6379
    timeout: 5000
    database: 0
    password: 123456
    jedis:
      pool:
        max-idle: -1
    host: 127.0.0.1



server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/lff/talent_recommendation_system/entity

